apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: gke-metadata
  namespace: kube-system
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - NET_ADMIN
    - NET_BIND_SERVICE
    endpoints:
    - direction: inbound
      endpoint: :989/healthz
      headers:
        Connection:
        - close
        Host:
        - 127.0.0.1:989
      internal: false
      methods:
      - GET
    - direction: outbound
      endpoint: :80/computeMetadata/v1/instance/credentials/mds-client-certificate
      headers:
        Accept-Encoding:
        - gzip
        Host:
        - metadata.google.internal
      internal: false
      methods:
      - GET
    execs: null
    identifiedCallStacks: null
    imageID: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metadata-server@sha256:0540ea9dca33cdd4b4f3805b7fd7a2ed761492c038a047dd169da69b135a6272
    imageTag: europe-west1-artifactregistry.gcr.io/gke-release/gke-release/gke-metadata-server@sha256:0540ea9dca33cdd4b4f3805b7fd7a2ed761492c038a047dd169da69b135a6272
    name: gke-metadata-server
    opens:
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /dev/null
    - flags:
      - O_RDWR
      - O_CLOEXEC
      path: /dev/tpm0
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/hosts
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/nsswitch.conf
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/passwd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/resolv.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/srv/kubernetes/pki/ca-certificates.crt
    - flags:
      - O_RDONLY
      - O_DIRECTORY
      - O_CLOEXEC
      path: /etc/ssl/certs
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /etc/ssl/certs/ca-certificates.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /gke-metadata-server
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /home/kubernetes/bin/gke-exec-auth-plugin
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/cgroup
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/mountinfo
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/net/core/somaxconn
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/netstat
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /proc/⋯/net/snmp
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/task/1/fd
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/devices/virtual/dmi/id/product_name
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /sys/firmware/efi/efivars/InstanceRootCACertificate-a2858e46-a37f-456a-8c79-0c1fe48b65ff
    - flags:
      - O_RDONLY
      path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
    - flags:
      - O_RDONLY
      path: /usr/share/zoneinfo/America/Los_Angeles
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/lib/kubelet/kubeconfig
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/lib/kubelet/pki/kubelet-client.crt
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/lib/kubelet/pki/kubelet-client.key
    - flags:
      - O_RDONLY
      - O_CREAT
      - O_CLOEXEC
      path: /var/lib/kubelet/pki/kubelet-client.lock
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/containerd/io.containerd.runtime.v2.task/k8s.io/56cef0bc282b629b807146b8cc5123fdd3a11a9565f60ab9d2686c4703ef4af1/rootfs/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod694b0737_1742_4b16_8f56_6d178006c493.slice/cri-containerd-56cef0bc282b629b807146b8cc5123fdd3a11a9565f60ab9d2686c4703ef4af1.scope/cpu.max
    - flags:
      - O_RDONLY
      - O_CLOEXEC
      path: /var/run/containerd/io.containerd.runtime.v2.task/k8s.io/740d9c0ad52d601319da0f3a16cd4c545b7ca5019cf83ab1746a7eb61134711b/rootfs/sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podc266421e_5d16_4b9f_bd3a_3c22b1603bfb.slice/cri-containerd-740d9c0ad52d601319da0f3a16cd4c545b7ca5019cf83ab1746a7eb61134711b.scope/cpu.max
    - flags:
      - O_RDWR
      - O_CREAT
      - O_CLOEXEC
      path: /var/run/gkemds.gke.io/csi/volumes.boltdb
    rulePolicies:
      R0001: {}
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - clone
    - clone3
    - close
    - close_range
    - connect
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - eventfd2
    - execve
    - exit
    - exit_group
    - faccessat
    - faccessat2
    - fchdir
    - fchmodat
    - fchownat
    - fcntl
    - fdatasync
    - flock
    - fsconfig
    - fsmount
    - fsopen
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - geteuid
    - getpeername
    - getpid
    - getppid
    - getrandom
    - getrlimit
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - inotify_init1
    - ioctl
    - keyctl
    - listen
    - madvise
    - mkdirat
    - mknodat
    - mmap
    - mount
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - open_tree
    - openat
    - openat2
    - pidfd_open
    - pidfd_send_signal
    - pipe2
    - pivot_root
    - ppoll
    - prctl
    - pread64
    - prlimit64
    - pwrite64
    - read
    - readlink
    - readlinkat
    - recvfrom
    - rseq
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - sched_getaffinity
    - sched_yield
    - sendto
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setsid
    - setsockopt
    - setuid
    - sigaltstack
    - socket
    - statfs
    - statx
    - symlinkat
    - tgkill
    - umask
    - umount2
    - uname
    - unlinkat
    - waitid
    - write

